export const REPORT_MARKER = '<!-- maintainer-signal-report -->';

const RISK_LABELS = {
  low: '🟢 Low',
  moderate: '🟡 Moderate',
  high: '🟠 High',
  critical: '🔴 Critical'
};

function escapeCell(value) {
  return String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function list(items, emptyText) {
  if (!items || items.length === 0) {
    return `- ${emptyText}`;
  }

  return items.map((item) => `- ${item}`).join('\n');
}

function renderSignals(signals) {
  if (!signals.length) {
    return '- No elevated deterministic risk signals were detected.';
  }

  return signals
    .map((signal) => `- **+${signal.points} ${signal.title}:** ${signal.evidence}`)
    .join('\n');
}

function renderAi(ai) {
  if (!ai) return '';

  const concerns = list(ai.concerns, 'No additional semantic concerns.');
  const tests = list(ai.tests, 'No additional test scenarios suggested.');

  return `
## AI-assisted review

${ai.summary}

### Semantic concerns
${concerns}

### Suggested tests
${tests}

### Draft release note
${ai.releaseNote || 'No draft release note generated.'}
`;
}

export function renderReport(analysis, ai = null) {
  const { pullRequest, stats, risk, signals, checklist, releaseRecommendation } = analysis;

  return `${REPORT_MARKER}
# MaintainerSignal maintainer brief

> Deterministic risk: **${RISK_LABELS[risk.level]} (${risk.score}/12)**

| Pull request | Author | Files | Additions | Deletions |
|---|---:|---:|---:|---:|
| ${escapeCell(pullRequest.title)} | @${escapeCell(pullRequest.author)} | ${stats.files} | +${stats.additions} | -${stats.deletions} |

## Why this score

${renderSignals(signals)}

## Maintainer checklist

${checklist.map((item) => `- [ ] ${item}`).join('\n')}

## Release impact

${releaseRecommendation}
${renderAi(ai)}
---
<sub>Generated by MaintainerSignal. Evidence is advisory; maintainers make the final decision.</sub>`;
}
