export const REPORT_MARKER = '<!-- maintainer-signal-report -->';
const LABELS = { low: '🟢 Low', moderate: '🟡 Moderate', high: '🟠 High', critical: '🔴 Critical' };
const escapeCell = (value) => String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
const list = (items, empty) => items?.length ? items.map((item) => `- ${item}`).join('\n') : `- ${empty}`;

export function renderReport(analysis, ai = null) {
  const { pullRequest, stats, risk, signals, checklist, releaseRecommendation } = analysis;
  const aiBlock = ai ? `\n## AI-assisted review\n\n${ai.summary}\n\n### Semantic concerns\n${list(ai.concerns, 'No additional semantic concerns.')}\n\n### Suggested tests\n${list(ai.tests, 'No additional test scenarios.')}\n\n### Draft release note\n${ai.releaseNote || 'No draft release note generated.'}\n` : '';
  return `${REPORT_MARKER}\n# MaintainerSignal maintainer brief\n\n> Deterministic risk: **${LABELS[risk.level]} (${risk.score}/12)**\n\n| Pull request | Author | Files | Additions | Deletions |\n|---|---:|---:|---:|---:|\n| ${escapeCell(pullRequest.title)} | @${escapeCell(pullRequest.author)} | ${stats.files} | +${stats.additions} | -${stats.deletions} |\n\n## Why this score\n\n${signals.length ? signals.map((s) => `- **+${s.points} ${s.title}:** ${s.evidence}`).join('\n') : '- No elevated deterministic risk signals were detected.'}\n\n## Maintainer checklist\n\n${checklist.map((item) => `- [ ] ${item}`).join('\n')}\n\n## Release impact\n\n${releaseRecommendation}${aiBlock}\n---\n<sub>Generated by MaintainerSignal. Evidence is advisory; maintainers make the final decision.</sub>`;
}
